name: CI/CD for Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token $HF_TOKEN
          
          # Create the space repository with --yes flag to bypass the confirmation prompt
          huggingface-cli repo create eman1234/text-summarization --type space --yes
          
          # Clone the space repository
          git clone https://huggingface.co/spaces/eman1234/text-summarization
          
          # Copy the content of your current repo to the Hugging Face space repo
          cp -r ./* eman1234/text-summarization/
          
          # Navigate to the space directory
          cd eman1234/text-summarization
          
          # Commit and push the changes
          git add .
          git commit -m "Deploy Gradio App"
          git push
