name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Add Hugging Face remote repository
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: |
          git remote add space https://huggingface:$HF@huggingface.co/spaces/eman1234/text-summarization

      # Step 3: Push code to Hugging Face Space
      - name: Push to Hugging Face Hub
        env:
          HF: ${{ secrets.HF }}
        run: |
          git push --force https://huggingface:$HF@huggingface.co/spaces/eman1234/text-summarization main
