name: CI/CD for Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Install Hugging Face CLI and required libraries
          pip install huggingface_hub

          # Log in to Hugging Face
          echo $HF_TOKEN | huggingface-cli login --token

          # Define space variables
          SPACE_NAME="eman1234/text-summarization"

          # Create the Hugging Face Space if it doesn't exist
          python - <<EOF
from huggingface_hub import HfApi

api = HfApi()
try:
    api.create_repo(name="$SPACE_NAME", repo_type="space", exist_ok=True)
    print(f"Space '{SPACE_NAME}' created or already exists.")
except Exception as e:
    print(f"Error creating space: {e}")
EOF

          # Clone the Hugging Face Space repository
          git clone https://huggingface.co/spaces/$SPACE_NAME

          # Copy all files to the space repository
          rsync -av --exclude '.git' ./ $SPACE_NAME/

          # Commit and push changes
          cd $SPACE_NAME
          git add .
          git commit -m "Deploy Gradio App" || echo "No changes to commit"
          git push
